name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o Burp-Updater.exe main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Burp-Updater.exe
        path: Burp-Updater.exe

